# Generated by Django 5.1 on 2024-11-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewContents', models.TextField()),
                ('userRatings', models.PositiveSmallIntegerField()),
                ('modelRatings', models.PositiveSmallIntegerField(null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
